### ISSUE TITLE
Powercord crash loops

### ISSUE THREAD

**Issue by Twizzer** [Juby210/bdCompat#10]
Recent Canary Update + BDCompat causes crash looping on powercord.

**Comment by Juby210** [comment]
BDCompat itself doesn't cause any issues, only plugins may cause a loop. Already looked a bit and fixing them would require some time and the best option is to wait for BD fix for canary to see what changes it would have.

**Comment by Juby210** [comment]
Should be resolved now by recent powercord & bdCompat update.
