### ISSUE TITLE
BD plugins no longer working

### ISSUE THREAD

**Issue by siu3334** [Juby210/bdCompat#11]
Hi,

I am using bdCompat to use few of BD plugins with powercord, mainly by Zerebos and DevilBro. Even though plugins are loaded, they don't seem to function as per each plugin's respective feature. All of these plugins used to work just fine before the recent Discord changes which broke powercord as whole. Now they don't.

These are the plugins I am using currently:
![30-Jan-2021_12-21-14](https://user-images.githubusercontent.com/24418520/106349682-e5645700-62f5-11eb-8b15-7808c7b02004.png)

I'm not sure if it's an issue with bdCompat itself or with individual BD plugins so I decided to open an issue. :P

Discord version: Canary 75603 (8689edd)
Host 0.0.118
Linux 64-Bit (5.9.0-0.Bpo.5-Amd64)
Powercord v2 (472e4e2)

**Comment by Juby210** [comment]
- `HideDisabledEmojis` can be replaced with https://github.com/NurMarvin/discord-tweaks
- `ImageUtilities` can be replaced with Lighty's [BetterImageViewer](https://github.com/1Lighty/BetterDiscordPlugins/blob/master/Plugins/BetterImageViewer/BetterImageViewer.plugin.js) + https://github.com/lorencerri/powercord-reverse-image-search
- `PermissionsViewer` and `RoleMembers` works fine 
![image](https://user-images.githubusercontent.com/31005896/106354761-6c183480-62f4-11eb-905c-9d12a417a63a.png)
- `ShowHiddenChannels` - i don't support it ¯\_(ツ)_/¯

**Comment by siu3334** [comment]
Thanks.
