### ISSUE TITLE
Error with Twemoji (Micelle) and Zlibrary

### ISSUE THREAD

**Issue by Mara-Li** [Juby210/bdCompat#12]
I try to use this plugin : https://github.com/micelle/BetterDiscordPlugins/blob/master/plugins/Twemoji.plugin.js (work fine, for the moment, with BD) with BDcompact, but when loading I have this error : 
![image](https://user-images.githubusercontent.com/30244939/109494788-a65d2900-7a8e-11eb-8245-bc4854832b81.png)

Are they a workaround ? The plugin doesn't exist at all on powercord, and help me a lot because a lot of serv on discord use emoji in name/channel name.

**Comment by Juby210** [comment]
Closing because there is powercord alternative to this plugin https://github.com/Vendicated/PowercordTwemojiEverywhere
