### ISSUE TITLE
BD plugin ServerFolders extra column not working.

### ISSUE THREAD

**Issue by hoyupu** [Juby210/bdCompat#15]
In the settings for ServerFolders, there's a toggle option - "Moves the Servers from opened Folders in an extra Column"

This should move all servers from an opened folder into another column to the side, which pops out upon opening them. For some reason, it doesn't seem to be working here, which sucks. Is there a way to fix this?

**Comment by Juby210** [comment]
use https://github.com/Juby210/better-folders
