### ISSUE TITLE
ayo

### ISSUE THREAD

**Issue by JunjoSick** [Juby210/bdCompat#16]
The plugin no longer works with ShowHiddenChannels v2.9.7

**Comment by Juby210** [comment]
> ### 3. Do not attempt to circumvent Discord permissions
> Any data processed from Discord API endpoints must be processed the same way as it is by the Discord client UI.
For example, displaying channels that the Discord client would otherwise hide is prohibited.
This also applies to restrictions put in place by Discord on legal or any other serious matters, such as the NSFW age gate.

https://powercord.dev/guidelines
