### ISSUE TITLE
Doesnt work with latest discord canary

### ISSUE THREAD

**Issue by Dragonisser** [Juby210/bdCompat#19]
It appears as discord changed something today that broke everything.

**Comment by Spencer-0003** [comment]
I think I'm having the same issue.
![image](https://user-images.githubusercontent.com/36741900/125372674-967a1d80-e37b-11eb-83d7-99e8c49b8579.png)

**Comment by psychedelic-fox** [comment]
same problem here, same errors in the settings page.

seems to only be an issue with plugins relying on `0BDFDB` but opening an [issue](https://github.com/mwittrien/BetterDiscordAddons/issues/946) there left a pretty unhelpful and dismissive response.

I'm not entirely sure if this is a problem with Powercord, 0BDFDB, or bdCompat unfortunately. here's hoping some fix comes out soon.

**Comment by Dragonisser** [comment]
Its probably a mixture of both. Tho right now its most likely bdcompat that needs to do a move to fix it, since its not just bdfdb that doesnt load, but everything else too.

**Comment by Juby210** [comment]
Plugin error, not related to bdCompat.
