### ISSUE TITLE
BDFDB completey breaks custom banners

### ISSUE THREAD

**Issue by HexaRG** [Juby210/bdCompat#30]
custom banner images/gifs are not rendered and the pfp is misplaced over the username,
this happens regardless of where the banner is being displayed, however, solid color banners work perfectly fine

this is how custom banners appear when BDFDB is **enabled**:
![image](https://user-images.githubusercontent.com/67880600/141888198-d2bb81bd-1501-4c89-8b8f-9870f5db6125.png)
this is how custom banners appear when BDFDB is **disabled**:
![image](https://user-images.githubusercontent.com/67880600/141888787-ab1cb90a-0228-4a8f-9d04-c22146c14acb.png)

i've disabled every plugin and theme excluding bdCompat & BDFDB and this issue remained
![image](https://user-images.githubusercontent.com/67880600/141890214-8d9580fb-0ecc-432e-a40a-eae1a781194b.png)

another thing to note is that none of my friends had this rendering issue

**Comment by Juby210** [comment]
BDFDB's issue, not bdCompat's
