### ISSUE TITLE
Missing value in BdAPI.findModule

### ISSUE THREAD

**Issue by User9684** [Juby210/bdCompat#37]
Attempting to do `const UserInfoBase = BdApi.findModule(m => m.default.displayName === "UserInfoBase")` will result in the error `TypeError: Cannot read property 'displayName' of undefined`
(aka m.default doesnt exist)

**Comment by Juby210** [comment]
How is that issue related to bdCompat. Your filter function has an error, correct filter function would be `m => m.default?.displayName === "UserInfoBase"`

**Comment by Juby210** [comment]
Or does betterdiscord try catch filters? But still filter function has an error causing it is slower than it should be.

**Comment by User9684** [comment]
No, that function works perfectly fine on normal BD

**Comment by User9684** [comment]
The issue this is happening on is with the Apate plugin, which works on BD fine, but not on BDCompat.

**Comment by User9684** [comment]
I may have erroring code incorrectly, I'll check

**Comment by User9684** [comment]
Sorry bout this, I just saw the error and assumed that it was missing the value, didn't expect BD to try catch their functions.
