### ISSUE TITLE
"Failed to load powercord module manager's details component!"

### ISSUE THREAD

**Issue by ivan123-tty** [Juby210/bdCompat#44]
![image](https://user-images.githubusercontent.com/70339505/186946615-75d6bbd5-cd36-4f4d-9fa8-82ac185bef6b.png)

**Comment by ivan123-tty** [comment]
a bit more info:
i'm using replugged

**Comment by Juby210** [comment]
fixed by #41

**Comment by checkraisefold** [comment]
v0.3.12 caused this issue to start happening for me running Replugged migrated from Powercord install
locally reverting https://github.com/Juby210/bdCompat/commit/ad58368b2a4c0e33d6a2de1033cf1969b9751a6f fixed the issue
