### ISSUE TITLE
PluginRepo - 0BDFDB failing

### ISSUE THREAD

**Issue by nihaals** [Juby210/bdCompat#8]
[PluginRepo](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/PluginRepo) provides an easy way to update BD plugins (and find new ones, install new ones etc.) but fails when fetching the plugin list:

![image](https://user-images.githubusercontent.com/18350092/99879757-b7340e00-2c06-11eb-8858-1c4b0d1a2ce6.png)

I'm not sure if this is due to the security changes mentioned in #5 or just a difference in what Powercord exposes

**Comment by Juby210** [comment]
Electron remote is unsupported on powercord, nothing to do on my side.
