### ISSUE TITLE
My plugins config doesnt show up, and the plugins dont work.

### ISSUE THREAD

**Issue by zisis912** [Juby210/bdCompat#9]
I installed bdCompat, and put my plugins in the correct place. When I go to settings, they are there. I turn them on, they say plugin has started. I go to settings, but their settings to change the config are completely broken. Even if I bring my BD config there, the plugins still wont even work. This happens with 70% of my plugins. Most of them that dont work are made by devilbro and zerebros. I have 2 plugins made from l0c4lh057, one works and the other doesn't. Could someone help me?

**Comment by Juby210** [comment]
Hey, test this on bd on discord canary first - same result! How would i fix this if this is plugin issue and not bdCompat?

**Comment by zisis912** [comment]
@Juby210 oh its a canary issue, though it was a bdcompat issue
